import Head from "next/head";
import { Body } from "../containers";

const Index: React.FC = () => {
  return (
    <div>
      <Head>
        <title>CryptoSite-NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Body />
      </div>
    </div>
  );
};

export default Index;
