import Head from "next/head";
import styles from "../styles/index.module.scss";
import layout from "../styles/layout.module.scss";
import { Body, Navbar, SideMenu, Footer } from "../containers";

export default function Index() {
  return (
    <div>
      <Head>
        <title>CryptoSite-NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Body />
      </div>
    </div>
  );
}
